# Generated by Django 4.2.2 on 2023-07-07 04:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=100)),
                ('personas_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_entrada', models.CharField(max_length=200)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('conciert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concierto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Concierto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concierto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entrada')),
            ],
        ),
    ]
