# Generated by Django 4.2.2 on 2023-06-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_concierto_entrada_alter_ingreso_nombre_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
